# Generated by Django 4.0.6 on 2022-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_active_employee_address_employee_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
